site_name: Mesh Guide

theme:
  name: kpn

extra_css:
  - css/custom.css

extra_javascript:
  - js/hljs-no-guess.js

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      guess_lang: false
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Reticulum: reticulum.md
  - RNode Setup: rnode.md
  - Companion Software: companion-software.md
  - LoRa Settings Comparison: lora-comparison.md

